// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddExcludeRule(arg1:models.ExcludeRule):Promise<void>;

export function Compare(arg1:string,arg2:string):Promise<models.CompareResult>;

export function ExportDiffs(arg1:Array<models.DiffItem>,arg2:string):Promise<void>;

export function ExportToZip(arg1:Array<models.DiffItem>,arg2:string,arg3:string):Promise<string>;

export function GetConfig():Promise<models.Config>;

export function GetExcludeRules():Promise<Array<models.ExcludeRule>>;

export function GetTextDiff(arg1:string,arg2:string,arg3:string):Promise<models.TextDiff>;

export function GetZipRootFolder(arg1:string):Promise<string>;

export function RemoveExcludeRule(arg1:number):Promise<void>;

export function ResetExcludeRules():Promise<void>;

export function SaveConfig(arg1:models.Config):Promise<void>;

export function SelectOutputDir():Promise<string>;

export function SelectWorkDir():Promise<string>;

export function SelectZipFile():Promise<string>;

export function SetExcludeRules(arg1:Array<models.ExcludeRule>):Promise<void>;
