// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExcludeRule(arg1) {
  return window['go']['main']['App']['AddExcludeRule'](arg1);
}

export function Compare(arg1, arg2) {
  return window['go']['main']['App']['Compare'](arg1, arg2);
}

export function ExportDiffs(arg1, arg2) {
  return window['go']['main']['App']['ExportDiffs'](arg1, arg2);
}

export function ExportToZip(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportToZip'](arg1, arg2, arg3);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetExcludeRules() {
  return window['go']['main']['App']['GetExcludeRules']();
}

export function GetTextDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTextDiff'](arg1, arg2, arg3);
}

export function GetZipRootFolder(arg1) {
  return window['go']['main']['App']['GetZipRootFolder'](arg1);
}

export function RemoveExcludeRule(arg1) {
  return window['go']['main']['App']['RemoveExcludeRule'](arg1);
}

export function ResetExcludeRules() {
  return window['go']['main']['App']['ResetExcludeRules']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function SelectWorkDir() {
  return window['go']['main']['App']['SelectWorkDir']();
}

export function SelectZipFile() {
  return window['go']['main']['App']['SelectZipFile']();
}

export function SetExcludeRules(arg1) {
  return window['go']['main']['App']['SetExcludeRules'](arg1);
}
